/*******************************************************************************
 * REQUEST HUB
 * =============================================================================
 * Copyright (C) 2026 Lucas Finoti <lucas.finoti@protonmail.com>
 *
 * This file is part of RequestHub.
 *
 * RequestHub is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 *
 * RequestHub is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RequestHub. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 ******************************************************************************/

#include "headers_view.h"
#include "../components/kv_list_view.h"

#define HEADER_FIXED_TOOLTIP                                                   \
  "This header is automatically generated by the client.\n"                    \
  "It cannot be altered or removed."

struct _HeadersView {
  GtkBox parent_instance;
  KvListView *kv;
};

G_DEFINE_TYPE(HeadersView, headers_view, GTK_TYPE_BOX)

static void headers_view_class_init(HeadersViewClass *klass) { (void)klass; }

static void headers_view_init(HeadersView *self) {
  gtk_orientable_set_orientation(GTK_ORIENTABLE(self),
                                 GTK_ORIENTATION_VERTICAL);

  KvListViewConfig config = {
      .title = "Headers",
      .add_button_label = "Add",
      .clear_button_label = "Delete all",
      .key_placeholder = "header",
      .value_placeholder = "value",
      .add_prepends = FALSE,
  };

  self->kv = kv_list_view_new(&config);
  gtk_widget_set_vexpand(GTK_WIDGET(self->kv), TRUE);
  gtk_widget_set_hexpand(GTK_WIDGET(self->kv), TRUE);
  gtk_box_append(GTK_BOX(self), GTK_WIDGET(self->kv));
}

HeadersView *headers_view_new(void) {
  HeadersView *self = g_object_new(TYPE_HEADERS_VIEW, NULL);

  kv_list_view_add_fixed(self->kv, "Accept", "*/*", HEADER_FIXED_TOOLTIP);
  kv_list_view_add_fixed(self->kv, "Host", "<calculated at runtime>",
                         HEADER_FIXED_TOOLTIP);
  kv_list_view_add_editable(self->kv, "User-Agent", "requesthub/0.0.1");

  return self;
}

static void apply_header_to_request(const char *key, const char *value,
                                    gpointer user_data) {
  if (g_strcmp0(key, "Host") == 0) {
    return;
  }
  HttpRequest *request = user_data;
  gchar *line = g_strdup_printf("%s: %s", key, value);
  http_request_add_header(request, line);
  g_free(line);
}

void headers_view_apply_to_request(HeadersView *self, HttpRequest *request) {
  g_return_if_fail(HEADERS_IS_VIEW(self));
  g_return_if_fail(request != NULL);

  kv_list_view_for_each(self->kv, KV_LIST_ITER_ALL, apply_header_to_request,
                        request);
}

void headers_view_clear_all(HeadersView *self) {
  g_return_if_fail(HEADERS_IS_VIEW(self));
  kv_list_view_clear_editable(self->kv);
}

void headers_view_for_each(HeadersView *self,
                           void (*func)(const char *key, const char *value,
                                        gpointer user_data),
                           gpointer user_data) {
  g_return_if_fail(HEADERS_IS_VIEW(self));
  kv_list_view_for_each(self->kv, KV_LIST_ITER_EDITABLE, func, user_data);
}

void headers_view_add_pair(HeadersView *self, const char *key,
                           const char *value) {
  g_return_if_fail(HEADERS_IS_VIEW(self));
  kv_list_view_add_editable(self->kv, key, value);
}
