/*******************************************************************************
 * Copyright (C) 2026 Lucas Finoti <lucas.finoti@protonmail.com>
 *
 * This file is part of RequestHub.
 *
 * RequestHub is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 *
 * RequestHub is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RequestHub. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 ******************************************************************************/

#include "request_view.h"
#include "../panels/request_tabs.h"
#include "../panels/body_panel.h"
#include "../components/kv_list_view.h"
#include "../../config/version.h"

#define REQUEST_VIEW_MIN_WIDTH 380

#define HEADER_FIXED_TOOLTIP                                                   \
  "This header is automatically generated by the client.\n"                    \
  "It cannot be altered or removed."

struct _RequestView {
  GtkBox parent_instance;
  RequestTopBar *top_bar;
  RequestTabs *tabs;
  KvListView *params_list;
  KvListView *headers_list;
  BodyPanel *body_panel;
};

G_DEFINE_FINAL_TYPE(RequestView, request_view, GTK_TYPE_BOX)

static KvListView *build_params_list(void) {
  static const KvListViewConfig config = {
      .title = "Query parameters",
      .add_button_label = "Add",
      .clear_button_label = "Delete all",
      .key_placeholder = "name",
      .value_placeholder = "value",
      .add_prepends = TRUE,
  };
  KvListView *list = kv_list_view_new(&config);
  gtk_widget_set_vexpand(GTK_WIDGET(list), TRUE);
  gtk_widget_set_hexpand(GTK_WIDGET(list), TRUE);
  return list;
}

static KvListView *build_headers_list(void) {
  static const KvListViewConfig config = {
      .title = "Headers",
      .add_button_label = "Add",
      .clear_button_label = "Delete all",
      .key_placeholder = "header",
      .value_placeholder = "value",
      .add_prepends = FALSE,
  };
  KvListView *list = kv_list_view_new(&config);
  gtk_widget_set_vexpand(GTK_WIDGET(list), TRUE);
  gtk_widget_set_hexpand(GTK_WIDGET(list), TRUE);

  kv_list_view_add_fixed(list, "Accept", "*/*", HEADER_FIXED_TOOLTIP);
  kv_list_view_add_fixed(list, "Host", "<calculated at runtime>",
                         HEADER_FIXED_TOOLTIP);
  kv_list_view_add_editable(list, "User-Agent", REQUESTHUB_USER_AGENT);
  return list;
}

static void request_view_init(RequestView *self) {
  gtk_orientable_set_orientation(GTK_ORIENTABLE(self),
                                 GTK_ORIENTATION_VERTICAL);
  gtk_widget_set_size_request(GTK_WIDGET(self), REQUEST_VIEW_MIN_WIDTH, -1);

  self->top_bar = request_top_bar_new();
  gtk_box_append(GTK_BOX(self), GTK_WIDGET(self->top_bar));

  self->tabs = request_tabs_new();
  gtk_box_append(GTK_BOX(self), GTK_WIDGET(self->tabs));

  self->params_list = build_params_list();
  request_tabs_add_view(self->tabs, GTK_WIDGET(self->params_list), "params",
                        "Params", "view-list-symbolic");

  self->body_panel = body_panel_new();
  request_tabs_add_view(self->tabs, GTK_WIDGET(self->body_panel), "body",
                        "Body", "text-x-generic-symbolic");

  self->headers_list = build_headers_list();
  request_tabs_add_view(self->tabs, GTK_WIDGET(self->headers_list), "headers",
                        "Headers", "preferences-system-symbolic");
}

static void request_view_class_init(RequestViewClass *klass) { (void)klass; }

RequestView *request_view_new(void) {
  return g_object_new(REQUEST_TYPE_VIEW, NULL);
}

RequestTopBar *request_view_get_top_bar(RequestView *self) {
  g_return_val_if_fail(REQUEST_IS_VIEW(self), NULL);

  return self->top_bar;
}


BodyPanel *request_view_get_body_panel(RequestView *self) {
  g_return_val_if_fail(REQUEST_IS_VIEW(self), NULL);
  return self->body_panel;
}

void request_view_apply_state(RequestView *self, const RequestState *state) {
  g_return_if_fail(REQUEST_IS_VIEW(self));
  if (state == NULL) {
    return;
  }

  request_top_bar_set_url(self->top_bar, request_state_get_url(state));
  request_top_bar_set_method(self->top_bar, request_state_get_method(state));

  body_panel_clear(self->body_panel);
  const char *body = request_state_get_body(state);
  if (body != NULL && *body != '\0') {
    body_panel_set_content(self->body_panel, body);
  }

  kv_list_view_clear_editable(self->params_list);
  guint query_count = request_state_query_count(state);
  for (guint i = 0; i < query_count; i++) {
    const char *k = request_state_query_key(state, i);
    const char *v = request_state_query_value(state, i);
    if (k != NULL) {
      kv_list_view_add_editable(self->params_list, k, v != NULL ? v : "");
    }
  }

  kv_list_view_clear_editable(self->headers_list);
  guint header_count = request_state_headers_count(state);
  for (guint i = 0; i < header_count; i++) {
    const char *k = request_state_header_key(state, i);
    const char *v = request_state_header_value(state, i);
    if (k != NULL) {
      kv_list_view_add_editable(self->headers_list, k, v != NULL ? v : "");
    }
  }
}

static void capture_header_to_state(const char *key, const char *value,
                                    gpointer user_data) {
  request_state_add_header((RequestState *)user_data, key, value);
}

static void capture_param_to_state(const char *key, const char *value,
                                   gpointer user_data) {
  request_state_add_query((RequestState *)user_data, key, value);
}

RequestState *request_view_capture_state(RequestView *self) {
  g_return_val_if_fail(REQUEST_IS_VIEW(self), NULL);

  RequestState *state = request_state_new();

  request_state_set_url(state, request_top_bar_get_url(self->top_bar));
  request_state_set_method(state, request_top_bar_get_method(self->top_bar));

  kv_list_view_for_each(self->headers_list, KV_LIST_ITER_EDITABLE,
                        capture_header_to_state, state);
  kv_list_view_for_each(self->params_list, KV_LIST_ITER_ALL,
                        capture_param_to_state, state);

  char *body = body_panel_get_content(self->body_panel);
  if (body != NULL && *body != '\0') {
    request_state_set_body(state, body);
  }
  g_free(body);

  return state;
}
