/*******************************************************************************
 * REQUEST HUB
 * =============================================================================
 * Copyright (C) 2026 Lucas Finoti <lucas.finoti@protonmail.com>
 *
 * This file is part of RequestHub.
 *
 * RequestHub is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 *
 * RequestHub is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RequestHub. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 ******************************************************************************/

#include "headers_panel.h"
#include "../components/kv_list_view.h"
#include "../../config/version.h"

#define HEADER_FIXED_TOOLTIP                                                   \
  "This header is automatically generated by the client.\n"                    \
  "It cannot be altered or removed."

struct _HeadersPanel {
  GtkBox parent_instance;
  KvListView *kv;
};

G_DEFINE_TYPE(HeadersPanel, headers_panel, GTK_TYPE_BOX)

static void headers_panel_class_init(HeadersPanelClass *klass) { (void)klass; }

static void headers_panel_init(HeadersPanel *self) {
  gtk_orientable_set_orientation(GTK_ORIENTABLE(self),
                                 GTK_ORIENTATION_VERTICAL);

  KvListViewConfig config = {
      .title = "Headers",
      .add_button_label = "Add",
      .clear_button_label = "Delete all",
      .key_placeholder = "header",
      .value_placeholder = "value",
      .add_prepends = FALSE,
  };

  self->kv = kv_list_view_new(&config);
  gtk_widget_set_vexpand(GTK_WIDGET(self->kv), TRUE);
  gtk_widget_set_hexpand(GTK_WIDGET(self->kv), TRUE);
  gtk_box_append(GTK_BOX(self), GTK_WIDGET(self->kv));
}

HeadersPanel *headers_panel_new(void) {
  HeadersPanel *self = g_object_new(TYPE_HEADERS_PANEL, NULL);

  kv_list_view_add_fixed(self->kv, "Accept", "*/*", HEADER_FIXED_TOOLTIP);
  kv_list_view_add_fixed(self->kv, "Host", "<calculated at runtime>",
                         HEADER_FIXED_TOOLTIP);
  kv_list_view_add_editable(self->kv, "User-Agent", REQUESTHUB_USER_AGENT);

  return self;
}

static void apply_header_to_request(const char *key, const char *value,
                                    gpointer user_data) {
  if (g_strcmp0(key, "Host") == 0) {
    return;
  }
  http_request_add_header((HttpRequest *)user_data, key, value);
}

void headers_panel_apply_to_request(HeadersPanel *self, HttpRequest *request) {
  g_return_if_fail(HEADERS_IS_PANEL(self));
  g_return_if_fail(request != NULL);

  kv_list_view_for_each(self->kv, KV_LIST_ITER_ALL, apply_header_to_request,
                        request);
}

void headers_panel_clear_all(HeadersPanel *self) {
  g_return_if_fail(HEADERS_IS_PANEL(self));
  kv_list_view_clear_editable(self->kv);
}

void headers_panel_for_each(HeadersPanel *self,
                           void (*func)(const char *key, const char *value,
                                        gpointer user_data),
                           gpointer user_data) {
  g_return_if_fail(HEADERS_IS_PANEL(self));
  kv_list_view_for_each(self->kv, KV_LIST_ITER_EDITABLE, func, user_data);
}

void headers_panel_add_pair(HeadersPanel *self, const char *key,
                           const char *value) {
  g_return_if_fail(HEADERS_IS_PANEL(self));
  kv_list_view_add_editable(self->kv, key, value);
}
