name: build-and-test-fedora

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:40

    steps:
      - run: |
          dnf install -y \
            gcc \
            make \
            pkgconf-pkg-config \
            git \
            glib2-devel \
            gtk4-devel \
            libadwaita-devel \
            gtksourceview5-devel \
            libxml2-devel \
            libyaml-devel \
            cjson-devel \
            libcurl-devel \
            libasan \
            libubsan

      - uses: actions/checkout@v4

      - run: make deps-check
      - run: make debug
      - run: make release

      - uses: actions/upload-artifact@v4
        with:
          name: requesthub-fedora
          path: |
            build/requesthub
            build/release/requesthub

  test:
    runs-on: ubuntu-latest

    container:
      image: fedora:40

    needs: build

    steps:
      - run: |
          dnf install -y \
            gcc \
            make \
            pkgconf-pkg-config \
            git \
            glib2-devel \
            cjson-devel \
            libcurl-devel \
            libasan \
            libubsan

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: requesthub-fedora

      - run: make test

      - name: Run network integration tests
        run: REQUESTHUB_NETWORK_TESTS=1 make test
        continue-on-error: true