name: build-and-test-ubuntu

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            pkg-config \
            libgtk-4-dev \
            libgtksourceview-5-dev \
            libxml2-dev \
            libyaml-dev \
            libcjson-dev \
            libcurl4-openssl-dev \
            libglib2.0-dev

      - run: make deps-check
      - run: make debug
      - run: make release

      - uses: actions/upload-artifact@v4
        with:
          name: requesthub-ubuntu
          path: |
            build/requesthub
            build/release/requesthub

  test:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            pkg-config \
            libgtk-4-dev \
            libgtksourceview-5-dev \
            libxml2-dev \
            libyaml-dev \
            libcjson-dev \
            libcurl4-openssl-dev \
            libglib2.0-dev

      - uses: actions/download-artifact@v4
        with:
          name: requesthub-ubuntu

      - run: make test